fix(analyics): Add ineligible reasons to app_switch_ineligible tracking
paypal/paypal-smart-payment-buttons pull request #224
Opened 2021-08-23 04:16 UTC by TNuzzi

2021-08-23 13:12 UTC, mnicpt commented on src/payment-flows/native/popup.js
> +                const ineligibilityReason = eligibility && eligibility[fundingSource] ? eligibility[fundingSource].ineligibilityReason : '';
```suggestion
                const ineligibilityReason = eligibility && eligibility[fundingSource] && eligibility[fundingSource].ineligibilityReason ? eligibility[fundingSource].ineligibilityReason : '';
```

2021-08-23 23:10 UTC, mnicpt approved these changes

2021-08-23 23:14 UTC, mnicpt requested changes
Need to condition eligibility on Venmo for the ineligibleReasons filtering.  So you want to have a case for PayPal, which would just be the result of `nativeEligibilityResults[fundingSource]?.eligble` and Venmo being what you have.

2021-08-23 23:43 UTC, bluepnume commented on src/payment-flows/native/native.js
> +    setupLogger({ env, sessionID, clientID, sdkCorrelationID, locale, sdkVersion, buyerCountry, fundingSource });
Why do we need to setup logger again? This should be happening when the buttons first render right?

2021-08-23 23:44 UTC, bluepnume commented on src/payment-flows/native/eligibility.js
> +    const eligible = ineligibleReasons?.every(reason => {
Should we limit this check to only desktop mode, for now?

2021-08-24 01:44 UTC, TNuzzi commented on src/payment-flows/native/native.js
> +    setupLogger({ env, sessionID, clientID, sdkCorrelationID, locale, sdkVersion, buyerCountry, fundingSource });
@bluepnume We found an instance where `fundingSource` was not being set when we wanted to log it.  It was in the `app_switch_ineligible`.  @mnicpt traced it back to trying to log it before the `fundingSource` was set.

@mnicpt Did I get that right?

2021-08-24 01:46 UTC, TNuzzi commented on src/payment-flows/native/eligibility.js
> +    const eligible = ineligibleReasons?.every(reason => {
@mnicpt has the details on this.  I pointed out to him that we were seeing `isBrowserMobileAndroid` and `isUserAgentEligible` on an iPad.

2021-08-24 01:46 UTC, TNuzzi commented on src/payment-flows/native/eligibility.js
> +    const eligible = ineligibleReasons?.every(reason => {
I think this code is temporary until @mnicpt did some refactoring in xobuyer.

2021-08-24 13:07 UTC, mnicpt commented on src/payment-flows/native/eligibility.js
> +    const eligible = ineligibleReasons?.every(reason => {
@TNuzzi Let's do what @bluepnume suggested.  This will keep this contained to desktop which is what we really want anyways.

2021-08-24 13:08 UTC, mnicpt commented on src/payment-flows/native/native.js
> +    setupLogger({ env, sessionID, clientID, sdkCorrelationID, locale, sdkVersion, buyerCountry, fundingSource });
@TNuzzi Instead of calling `setupLogger` again, let's add a tracking builder after `click`.  Spoke with @bluepnume  last night and he suggested.  Seems like the best option for handling this case.

2021-08-25 01:00 UTC, mnicpt commented on src/payment-flows/native/eligibility.js
> +        const ineligibleReasons = nativeEligibilityResults && nativeEligibilityResults[fundingSource]?.ineligibilityReason?.split(',');
```suggestion
        const ineligibleReasons = nativeEligibilityResults && nativeEligibilityResults[fundingSource]?.ineligibilityReason ? nativeEligibilityResults[fundingSource].ineligibilityReason.split(',') : '';
```

2021-08-25 01:02 UTC, mnicpt commented on src/payment-flows/native/eligibility.js
> +        const ineligibleReasons = nativeEligibilityResults && nativeEligibilityResults[fundingSource]?.ineligibilityReason?.split(',');
If `nativeEligibilityResults[fundingSource]?.ineligibilityReason` is empty, then eligible will be null which will be false and return false for eligibility.

2021-08-25 01:39 UTC, mnicpt commented on src/payment-flows/native/eligibility.js
> +            return eligibleReasons?.indexOf(reason) !== -1;
```suggestion
            return reason ? eligibleReasons?.indexOf(reason) !== -1 : true;
```

2021-08-25 01:39 UTC, mnicpt commented on src/payment-flows/native/eligibility.js
> +            return eligibleReasons?.indexOf(reason) !== -1;
Please do this to the other one too.

2021-08-25 12:45 UTC, mnicpt approved these changes

2021-08-25 15:00 UTC, merged