feat: log and track onError checkout calls
paypal/paypal-smart-payment-buttons pull request #240
Opened 2021-09-09 20:45 UTC by jscheinhorn

Track onError calls to determine flow interaction of proposed onError changes:

`onError: (err) => {
                // eslint-disable-next-line no-use-before-define
                return close().then(() => {
                    return onError(err);
                });
            },`

2021-09-09 23:57 UTC, jscheinhorn commented
Example tracking payload for onError call for sample order here: https://fpti-5x-3.pp-devcos-searchserv.us-central1.gcp.dev.paypalinc.com:5601/goto/53dcb4cd3d90c71da378b76ed5210539 


Using unique identifier for onError calls:
`transition_name`:`process_checkout_error `

2021-09-13 14:48 UTC, westeezy approved these changes
lgtm. I was going to mention maybe adding a test but given it'd be mostly mocks and we have a few passing tests [here](https://github.com/paypal/paypal-smart-payment-buttons/blob/1af8a7444acb6dc0ac911c869c9ff035061b37c9/test/client/error.js) I think this should be fine.

2021-09-16 16:47 UTC, mnicpt approved these changes

2021-09-16 16:48 UTC, mnicpt commented
@jscheinhorn I think this callback can be called prior to creating an order. If so, we don't want to call `createOrder`.

2021-09-16 16:58 UTC, bluepnume commented on src/payment-flows/checkout.js
> +                        .info('on_error_tracking')
Let's call this event `checkout_flow_error` `{ err: stringifyError(err) }` just to be a bit more specific.

2021-09-16 16:58 UTC, bluepnume commented on src/payment-flows/checkout.js
> +                            [FPTI_KEY.ERROR_DESC]:   JSON.stringify(err)
Please use `stringifyError` instead of `JSON.stringify`

2021-09-16 17:05 UTC, mnicpt reviewed
Left a comment...

2021-09-16 17:06 UTC, mnicpt requested changes
Left a comment...

2021-09-16 18:12 UTC, jscheinhorn commented on src/payment-flows/checkout.js
> +                        .info('on_error_tracking')
should we forego attempting to get the order ID (currently from createOrder) because of the above scenario (onError called in the event createOrder fails)?

2021-09-16 18:24 UTC, jscheinhorn commented on src/constants.js
> +    CHECKOUT_ERROR:           ('process_checkout_error' : 'process_checkout_error'),
change this too?
`CHECKOUT_ERROR:           ('checkout_flow_error' : 'checkout_flow_error'),`

2021-09-16 19:29 UTC, gregjopa commented on src/payment-flows/checkout.js
> +                        .info('on_error_tracking')
What do you think about wrapping `createOrder` in `Promise.try()` so the Promise never rejects? Ex:

```js
ZalgoPromise.try(createOrder)
    .then((orderID = 'unknown') => {
        getLogger()
        .info('on_error_tracking')
            .track({
                [FPTI_KEY.TRANSITION]:   FPTI_TRANSITION.CHECKOUT_ERROR,
                [FPTI_KEY.CONTEXT_TYPE]: FPTI_CONTEXT_TYPE.ORDER_ID,
                [FPTI_KEY.TOKEN]:        orderID,
                [FPTI_KEY.CONTEXT_ID]:   orderID,
                [FPTI_KEY.ERROR_DESC]:   JSON.stringify(err)
            }).flush();
        
        return onError(err);
    })
```

2021-09-16 19:31 UTC, bluepnume commented on src/payment-flows/checkout.js
> +                        .info('on_error_tracking')
> should we forego attempting to get the order ID (currently from createOrder) because of the above scenario (onError called in the event createOrder fails)?

Yeah I'd be happy to forego.

> What do you think about wrapping createOrder in Promise.try() so the Promise never rejects? Ex:

Quick note -- `Promise.try()` won't avoid a rejected promise. The only way to do that is to `.catch()` (and not re-throw)

2021-09-17 17:25 UTC, jscheinhorn commented
<img width="1409" alt="checkout_flow_error" src="https://user-images.githubusercontent.com/29203245/133829258-b3715f6d-e9fb-41f4-8fae-7a606c50dd39.png">

2021-09-20 17:47 UTC, jscheinhorn commented on src/constants.js
> +    CHECKOUT_ERROR:           ('process_checkout_error' : 'process_checkout_error'),
^ @bluepnume @mnicpt

2021-09-23 17:51 UTC, bluepnume commented on src/payment-flows/checkout.js
> +                    .info(`checkout_flow_error ${ { err: stringifyError(err) } }`)
```
.info(`checkout_flow_error`, { err: stringifyError(err) }`)
```

2021-09-23 17:52 UTC, bluepnume commented on src/payment-flows/checkout.js
> +                    .info(`checkout_flow_error ${ { err: stringifyError(err) } }`)
```suggestion
                    .info(`checkout_flow_error`, { err: stringifyError(err) }`)
```

2021-09-23 19:24 UTC, jscheinhorn commented on src/constants.js
> +    CHECKOUT_ERROR:           ('process_checkout_error' : 'process_checkout_error'),
kept as `CHECKOUT_ERROR:           ('process_checkout_error' : 'process_checkout_error'),`

2021-09-27 17:18 UTC, gregjopa approved these changes

2021-09-27 17:46 UTC, merged