Add reason survey before closing venmo QRcode modal.
paypal/paypal-smart-payment-buttons pull request #247
Opened 2021-09-15 16:43 UTC by andregardi

2021-09-16 02:55 UTC, remotevision commented on src/constants.js
> +    DESKTOP_EXIT_SURVEY_REASON: ('reason' : 'reason')
@andregardi can we make `reason` more descriptive? maybe just keep it at `desktop_exit_survey_reason`?

2021-09-16 12:12 UTC, andregardi commented on src/constants.js
> +    DESKTOP_EXIT_SURVEY_REASON: ('reason' : 'reason')
Sure we can @remotevision !
This `reason` name was suggested by the the instrumentation team, but I believe that using `desktop_exit_survey_reason` is a better solution. Thank you!

2021-09-19 19:29 UTC, mrbaguvix requested changes

2021-09-19 19:29 UTC, mrbaguvix commented on src/qrcode/qrcard.jsx
> +    );
Don't think we need to reassign the entire component? Can use directly.

2021-09-19 19:29 UTC, mrbaguvix commented on src/types.js
> +    onSubmitFeedback? : (reason : string) => void,
Should we declare a map type?
```suggestion
    onSubmitFeedback? : (reason : Reasons[]) => void,
```

2021-09-19 19:29 UTC, mrbaguvix commented on test/client/native-qrcode.js
> +                window.xprops.platform = PLATFORM.DESKTOP;
Would be better to break this unit tests into at least 2 assertions with _describe/it_ block

2021-09-20 12:39 UTC, andregardi commented on src/types.js
> +    onSubmitFeedback? : (reason : string) => void,
Thank you for your suggestion David.
The parameter on the `onSubmitFeedback` is actually one single reason, on singular. That means we intent this to be a string.

2021-09-20 14:27 UTC, andregardi commented on src/qrcode/qrcard.jsx
> +    );
Yes, using it directly would also work. But keep it out of the returning JSX help us to keep a clean code on conditional rendering elements and allow us to move its position more easily in future changes.

2021-09-20 19:47 UTC, bluepnume commented on src/payment-flows/native/qrcode.js
> +                getLogger().info(`VenmoDesktopPay_qrcode_survey`).track({
Can we just do this logging inside the survey component? Better to avoid having the parent care about this survey at all right?

2021-09-20 19:54 UTC, andregardi commented on src/payment-flows/native/qrcode.js
> +                getLogger().info(`VenmoDesktopPay_qrcode_survey`).track({
I like that idea!
I was just following the pattern established on other events. But will be happy to move that to the component.

2021-09-20 20:39 UTC, mnicpt commented on src/qrcode/components.jsx
> +const radioSvg = (
Move all survey stuff into its own file.

2021-09-20 20:42 UTC, andregardi commented on src/qrcode/components.jsx
> +const radioSvg = (
Yes @mnicpt, I will be happy to do that!

2021-10-14 03:00 UTC, merged