Fix Native Logging
paypal/paypal-smart-payment-buttons pull request #254
Opened 2021-09-18 14:32 UTC by mnicpt

### Your checklist for this pull request
🚨 Please review the [guidelines for a good PR Description](https://www.pullrequest.com/blog/writing-a-great-pull-request-description/)

- [ ] Ensure you have a PR description that answers: What? Why? How?
- [ ] Link to any reference tickets if they are available. This includes Jira ticket or Github issues.
- [ ] Include any relevant screenshots for the change set if it modifies any visual functionality.
- [ ] Ensure you have added passing tests to cover new functionality, bug fixes, etc.

### Description

High level description of the change being made. Include any diagrams you have available.

#### What is being changed from a technical perspective?

#### Why are we making these changes? Include and reference tickets (Jira, Github Issue, etc)

### Reproduction Steps (if applicable)

### Screenshots (if applicable)

❤️  Thank you!

2021-09-18 21:53 UTC, bluepnume commented on src/button/logger.js
> -            [FPTI_KEY.STATE]:                        FPTI_STATE.BUTTON,
Why remove this?

2021-09-18 21:54 UTC, bluepnume commented on src/button/logger.js
> +            [FPTI_KEY.CONTEXT_TYPE]:                    FPTI_CONTEXT_TYPE.BUTTON_SESSION_ID,
Isn't this handled by the tracking builder already?

2021-09-18 21:54 UTC, bluepnume commented on src/button/pay.js
> +                    token: '-'
Can we make this `null` or `undefined`?

2021-09-18 21:54 UTC, bluepnume commented on src/button/pay.js
> +                    [FPTI_KEY.TOKEN]:        '-'
Same

2021-09-18 21:55 UTC, bluepnume commented on src/button/pay.js
> +                [FPTI_KEY.CONTEXT_TYPE]:   FPTI_CONTEXT_TYPE.BUTTON_SESSION_ID,
Again isn't this covered by the builder?

2021-09-18 21:56 UTC, bluepnume commented on src/payment-flows/native/native.js
> +                [FPTI_KEY.CONTEXT_TYPE]:   FPTI_CONTEXT_TYPE.BUTTON_SESSION_ID,
Can we do this in `pay.js` so it covers all payment flows?

2021-09-18 23:30 UTC, mnicpt commented on src/button/logger.js
> -            [FPTI_KEY.STATE]:                        FPTI_STATE.BUTTON,
It's a duplicate.

2021-09-18 23:34 UTC, mnicpt commented on src/payment-flows/native/native.js
> +                [FPTI_KEY.CONTEXT_TYPE]:   FPTI_CONTEXT_TYPE.BUTTON_SESSION_ID,
This log was getting hit before the one in pay.js and wasn't correct.

2021-09-18 23:35 UTC, mnicpt commented on src/payment-flows/native/native.js
> +                [FPTI_KEY.CONTEXT_TYPE]:   FPTI_CONTEXT_TYPE.BUTTON_SESSION_ID,
This is also for the the scenario when a subsequent button is tapped.

2021-09-18 23:42 UTC, mnicpt commented on src/button/pay.js
> +                    token: '-'
Just tested when setting to `null` and it doesn't reset and shows old token value.

2021-09-18 23:43 UTC, mnicpt commented on src/button/pay.js
> +                    token: '-'
Doing a reinstall to make sure I have the latest beaver-logger.

2021-09-18 23:52 UTC, mnicpt commented on src/button/pay.js
> +                    token: '-'
That worked.

2021-09-18 23:57 UTC, mnicpt commented on src/payment-flows/native/native.js
> +                [FPTI_KEY.CONTEXT_TYPE]:   FPTI_CONTEXT_TYPE.BUTTON_SESSION_ID,
It IS interesting that the popup_shown log gets hit first.

2021-09-18 23:58 UTC, mnicpt commented on src/payment-flows/native/native.js
> +                [FPTI_KEY.CONTEXT_TYPE]:   FPTI_CONTEXT_TYPE.BUTTON_SESSION_ID,
I see why.  We call the click on the flow first.

2021-09-19 00:08 UTC, mnicpt commented
@bluepnume Addressed all of your comments.  Much better!

2021-09-19 19:34 UTC, mrbaguvix requested changes

2021-09-19 19:34 UTC, mrbaguvix commented on src/button/pay.js
> +            })
Same as:
```suggestion
            .addPayloadBuilder(() => { token: null })
```

2021-09-19 19:34 UTC, mrbaguvix commented on src/button/pay.js
> +        clickPromise.catch(noop);
Lets expand more on the catch block, we should add a _console.error_ indicating _ZalgoPromise_

2021-09-19 20:09 UTC, bluepnume commented on src/button/logger.js
> -            [FPTI_KEY.STATE]:                        FPTI_STATE.BUTTON,
oh :D

2021-09-19 20:10 UTC, bluepnume approved these changes
LGTM!

2021-09-19 20:14 UTC, bluepnume commented on src/button/pay.js
> +        clickPromise.catch(noop);
In this case the error is actually handled later. This `.catch(noop)` is just to prevent `ZalgoPromise` throwing a "possibly unhandled error" before then.

We should consider adding a helper to `ZalgoPromise` to make this clearer, like `promise.lazy()` which inhibits "possibly unhandled error" for cases where we know `.catch()` will be called later. But let's take that out of the scope of this PR.

2021-09-20 13:52 UTC, merged