[Feature] - Venmo App label
paypal/paypal-smart-payment-buttons pull request #299
Opened 2021-11-15 20:47 UTC by fedperezp

### Description

### Why are we making these changes? Include references to any related Jira tasks or GitHub Issues

### Reproduction Steps (if applicable)

### Screenshots (if applicable)

### Dependent Changes (if applicable)

❤️  Thank you!

2021-11-16 19:56 UTC, mnicpt requested changes

2021-11-16 19:56 UTC, mnicpt commented on server/components/buttons/middleware.js
> +            const venmoAppLabelExperiment = await getVenmoAppLabelExperiment(req, { buttonSessionID });
Would be nice to make this generic and get all experiments and pass them along rather than one at a time.  Won't scale well.

2021-11-29 19:36 UTC, mnicpt commented on server/lib/get-experiments.js
> +/* @flow */
Why do we need this if we are fetching experiments from SCNW?

2021-11-29 20:20 UTC, fedperezp commented on server/lib/get-experiments.js
> +/* @flow */
this is to generate the default version of the experiment so we don't have issues with deploys, also so we have typings of the experiments on this file. let me know if you think this is unnecessary

2021-12-16 16:09 UTC, mnicpt approved these changes

2022-01-07 13:57 UTC, mnicpt commented on server/lib/get-experiments.js
> +        isFundingSourceBranded:        false,
@fedperezp Is this an experiment?

2022-01-07 15:17 UTC, fedperezp commented on server/lib/get-experiments.js
> +        isFundingSourceBranded:        false,
yes, all the defaults added in here are elmo experiments

2022-01-25 04:32 UTC, TNuzzi approved these changes

2022-01-25 04:32 UTC, merged