WIP: Card holder name component
paypal/paypal-smart-payment-buttons pull request #307
Opened 2021-12-08 20:23 UTC by leogedler

### Description

Created new preact component and logic for the **optional** Card Holder's Name input for the card fields.

### Why are we making these changes? Include references to any related Jira tasks or GitHub Issues

For the card fields we need an optional hosted field for the card holder's name.

The name is not PCI compliance but for the auto-fill browser autofill feature all the card fields related inputs need to be on an iframe for it to work as expected.

### Reproduction Steps (if applicable)

This new input can be defined the same way as the `number`, `expiry` and `cvv` the difference is that this input is optional and if is not defined the card fields will be still submit-able.

This new component will only be applicable for the multi card fields meaning that this field won't be able to use in the current implementation for the single card fields. 

### Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/5726810/145278778-7abdb4f0-6492-48de-b961-3c3c483460dd.png)

### Dependent Changes (if applicable)

This change depends on a change in `paypal-checkout-components`.

- https://github.com/paypal/paypal-checkout-components/pull/1809

❤️  Thank you!

2021-12-22 00:12 UTC, nbierdeman requested changes
It's looking good so far, @leogedler! :godmode: 💻

2021-12-22 00:12 UTC, nbierdeman commented on src/card/lib/card-utils.js
> +        if (field === CARD_FIELD_TYPE.NAME  && gqlErrors.length) {
```suggestion
        if (field === CARD_FIELD_TYPE.NAME && gqlErrors.length) {
```

2021-12-22 00:12 UTC, nbierdeman commented on src/card/lib/card-utils.js
> +    if (typeof isNameValid === 'boolean' &&  !isNameValid) {
```suggestion
    if (typeof isNameValid === 'boolean' && !isNameValid) {
```

2021-12-22 00:12 UTC, nbierdeman commented on test/client/card-fields.js
> +        it('should render multi card fields with createOrder and optinal field card holder\'s name', async () => {
```suggestion
        it('should render multi card fields with createOrder and optional cardholder name field', async () => {
```

2022-01-03 18:08 UTC, leogedler commented on src/card/interface.js
> +            name:   cardNameFrame && cardExpiryFrame.isFieldValid() ? cardNameFrame.getFieldValue() : ''
@nbierdeman thanks for noticing this!, it was an error we shouldn't mix thoses.

I have pushed a fix for it.

2022-01-03 18:08 UTC, leogedler commented on src/card/lib/card-utils.js
> +    if (value.length >= 1 && value.length <= 255) {
@nbierdeman for now I think this is it.

@crookedneighbor told me that we shouldn't overcomplicate this and only check for at lest 1 character and just set a max length.

2022-01-03 22:25 UTC, leogedler commented on src/card/constants.js
> +    name:   'Card holder\'s name'
Changed

2022-01-03 22:25 UTC, leogedler commented on src/card/interface.js
> +        (cardNameFrame ? cardExpiryFrame.isFieldValid() : true)
Fixed

2022-01-03 22:26 UTC, leogedler commented on src/card/lib/card-utils.js
> +    if (typeof isNameValid === 'boolean' &&  !isNameValid) {
Changed

2022-01-03 22:28 UTC, leogedler commented on test/client/card-fields.js
> +        it('should render multi card fields with createOrder and optinal field card holder\'s name', async () => {
Changed

2022-01-03 22:36 UTC, leogedler commented on src/card/components/page.jsx
> +        } else if (type === CARD_FIELD_TYPE.NAME && errors && errors.length) {
@nbierdeman using a switch statement we cannot check for `errors && errors.length` and we need to check if that part is truty.

We could use a mix between a switch and some inner if/else but that will make it more complex so I don't think it worth it.

If you have another idea let me know.

2022-01-10 22:40 UTC, leogedler commented on src/card/components/page.jsx
> +        } else if (type === CARD_FIELD_TYPE.NAME && errors && errors.length) {
@nbierdeman I have changed this to a combination between an if/else and a switch.

2022-01-11 16:07 UTC, crookedneighbor commented on src/card/lib/card-utils.js
> +    if (typeof isNameValid === 'boolean' && !isNameValid) {
Can this be simplified to:

```suggestion
    if (isNameValid === false) {
```

2022-01-11 16:07 UTC, crookedneighbor commented on src/card/lib/card-utils.js
> +    if (value.length >= 1 && value.length <= 255) {
Yeah, the requirements for cardholder names are so loose, that we're bound to run into edge cases if we're too strict on it.

2022-01-11 16:07 UTC, crookedneighbor commented on src/card/interface.js
> +            name:   cardNameFrame && cardNameFrame.isFieldValid() ? cardNameFrame.getFieldValue() : ''
can you explain this extra logic here?

2022-01-11 17:10 UTC, leogedler commented on src/card/interface.js
> +            name:   cardNameFrame && cardNameFrame.isFieldValid() ? cardNameFrame.getFieldValue() : ''
@crookedneighbor they way SPB gets the value for each field from the iFrames is by getting the frames which has access to the `win.exports` (zoid). 

Here is the function use for this purpose ---> https://github.com/paypal/paypal-smart-payment-buttons/blob/master/src/card/interface.js#L16

Having access to the frame then we have access for the methods defined on [Page](https://github.com/paypal/paypal-smart-payment-buttons/blob/master/src/card/components/page.jsx) for each field.

For the particular case of the `name` field which is optional I'm adding a logic to first check if the frame was defined (meaning that the field was set by the user), checking validity and if true returning the field value.

2022-01-11 18:58 UTC, crookedneighbor commented on src/card/interface.js
> +            name:   cardNameFrame && cardNameFrame.isFieldValid() ? cardNameFrame.getFieldValue() : ''
Would this syntax work in flow? If the object exists, call `getFieldValue()` and default any falsy values to `""`.

```suggestion
            name:   cardNameFrame?.getFieldValue() || ''
```

2022-01-11 19:50 UTC, leogedler commented on src/card/interface.js
> +            name:   cardNameFrame && cardNameFrame.isFieldValid() ? cardNameFrame.getFieldValue() : ''
@crookedneighbor It worked, I'm pushing a change.

2022-01-21 23:35 UTC, nbierdeman approved these changes
Great work, @leogedler! This looks ready to merge (other than if you do end up needing to make changes to accommodate GQL). 🥳

2022-01-24 16:28 UTC, merged