unit tests for applepay utils
paypal/paypal-smart-payment-buttons pull request #323
Opened 2022-01-21 23:15 UTC by andyfen

![Screen Shot 2022-01-21 at 3 10 39 PM](https://user-images.githubusercontent.com/5710962/150611707-a8e3779d-2503-4e9f-87f6-0d6dbb184d7b.png)

- adds javascript.validate.enable to vscode config to stop it thinking the flow files are typescript 
- adds unit test for applepay utils 
- updates the checkout session type as it didn't seem right ? please confirm @mnicpt 
i see it as 
```
      "checkoutSession": {
            "allowedCardIssuers": [
                "MASTER_CARD",
                "DISCOVER",
                "VISA",
                "AMEX",
                "DINERS"
            ],
            "cart": {
                "amounts": {
                    "shippingAndHandling": {
                        "currencyValue": "4.99",
                        "currencySymbol": "$",
                        "currencyFormat": "$4.99"
                    },
                    "tax": {
                        "currencyValue": "0.07",
                        "currencySymbol": "$",
                        "currencyFormat": "$0.07"
                    },
                    "subtotal": {
                        "currencyValue": "1.99",
                        "currencySymbol": "$",
                        "currencyFormat": "$1.99"
                    },
                    "total": {
                        "currencyValue": "7.05",
                        "currencyCode": "USD",
                        "currencyFormatSymbolISOCurrency": "$7.05 USD"
                    }
                },
```

2022-01-26 20:03 UTC, andyfen commented on src/api/order.js
> +                    currencySymbol : string,
maybe 
```
currencySymbol : string,
```
should be ?
```
currencySymbol :  $Values<typeof CURRENCY>
```

2022-01-26 20:07 UTC, mnicpt commented on .gitignore
> -.vscode
Please leave this here so it doesn't accidentally get committed.  We don't want user's custom IDE settings. Be sure to leave an empty line at the end.

2022-01-26 20:08 UTC, mnicpt commented on .vscode/settings.json
> +{
Please just let this be for your workspace.

2022-01-26 20:17 UTC, mnicpt commented on src/api/order.js
> +                    currencySymbol : string,
Why are we changing these?

2022-01-26 20:17 UTC, mnicpt commented on src/payment-flows/applepay/__tests__/applepay-eligibility.test.js
> +    test('it should be elegible', () => {
Spelling....`eligible`

2022-01-26 20:18 UTC, mnicpt commented on src/payment-flows/applepay/__tests__/applepay-eligibility.test.js
> +    test('it should be elegible', () => {
Also, be more descriptive with regards to the Apple Pay eligibility.  Like `should be eligible when funding eligible`

2022-01-26 20:19 UTC, mnicpt commented on src/payment-flows/applepay/__tests__/applepay-eligibility.test.js
> +    test('it should not be elegible', () => {
`should be ineligible when funding ineligible`

2022-01-26 20:19 UTC, mnicpt commented on src/payment-flows/applepay/__tests__/applepay-eligibility.test.js
> +    test('should be elegible', () => {
`should be eligible when fundingSource is APPLEPAY`

2022-01-26 20:20 UTC, mnicpt commented on src/payment-flows/applepay/applepay.js
> +export function isApplePayEligible({ serviceData } : IsEligibleOptions) : boolean {
Why are you exporting these?  These are part of the flow interface are exported there.

2022-01-26 20:22 UTC, mnicpt requested changes
We do not do unit testing within flows but rather integration tests that describe system requirements.  Please write tests in the same fashion.  Also, do not export functions just so they can be unit tested.

2022-01-26 20:44 UTC, andyfen commented on .vscode/settings.json
> +{
this is required to prevent vscode interpreting the flow files as typescript https://stackoverflow.com/questions/48859169/js-types-can-only-be-used-in-a-ts-file-visual-studio-code-using-ts-check

2022-01-26 20:45 UTC, andyfen commented on src/payment-flows/applepay/applepay.js
> +export function isApplePayEligible({ serviceData } : IsEligibleOptions) : boolean {
so that they can be tested

2022-01-26 20:48 UTC, andyfen commented
> Also, do not export functions just so they can be unit tested.

i'm sorry ? they need to be unit tested, that will require the functions to be exported

2022-01-26 20:50 UTC, andyfen commented on .vscode/settings.json
> +{
its standard practice to include a .vscode package example https://github.com/facebook/jest/tree/main/.vscode

2022-01-26 21:04 UTC, mnicpt commented on .vscode/settings.json
> +{
You aren't setup correctly then.  It is not standard practice here that I have seen.  Did you run `npm run flow-typed`? None of us working in this repo need this to prevent VSCode from interpreting the Flow files as Typescript.

2022-01-26 21:06 UTC, mnicpt commented
Don't unit test.  Not necessary.  Test system requirements not nitty gritty.  You will still get the coverage you need if you cover the system requirements.

2022-01-26 21:08 UTC, mnicpt commented on src/payment-flows/applepay/applepay.js
> +export function isApplePayEligible({ serviceData } : IsEligibleOptions) : boolean {
No.  Need to test these as integration tests.  See tests in `happy.js` as a pattern to follow for testing the flows.  Exporting functions so they can be tested would be like making methods public in Java when they should be private so they can be tested.  Test private methods through public interfaces.  Don't break encapsulation.

2022-01-26 21:39 UTC, andyfen commented on src/api/order.js
> +                    currencySymbol : string,
because the type is incorrect for the checkoutSession, 
for `shippingAndHandling` `tax` `subtotal`  it should be `currencyValue` `currencySymbol`  `currencyFormat` 

only total uses `currencyFormatSymbolISOCurrency`

```
                "amounts": {
                    "shippingAndHandling": {
                        "currencyValue": "0.00",
                        "currencySymbol": "$",
                        "currencyFormat": "$0.00"
                    },
                    "tax": {
                        "currencyValue": "0.00",
                        "currencySymbol": "$",
                        "currencyFormat": "$0.00"
                    },
                    "subtotal": {
                        "currencyValue": "0.00",
                        "currencySymbol": "$",
                        "currencyFormat": "$0.00"
                    },
                    "total": {
                        "currencyValue": "7.05",
                        "currencyCode": "USD",
                        "currencyFormatSymbolISOCurrency": "$7.05 USD"
                    }
                },
```
this is the existing type `shippingAndHandling` `tax` `subtotal` are wrong
```
            amounts : {|
                shippingAndHandling : {|
                    currencyFormatSymbolISOCurrency : string,
                    currencyValue : string,
                    currencyCode : $Values<typeof CURRENCY>
                |},
                tax : {|
                    currencyFormatSymbolISOCurrency : string,
                    currencyValue : string,
                    currencyCode : $Values<typeof CURRENCY>
                |},
                subtotal : {|
                    currencyFormatSymbolISOCurrency : string,
                    currencyValue : string,
                    currencyCode : $Values<typeof CURRENCY>
                |},
                total : {|
                    currencyFormatSymbolISOCurrency : string,
                    currencyValue : string,
                    currencyCode : $Values<typeof CURRENCY>
                |}
            |},
```

2022-01-26 21:40 UTC, bluepnume commented on src/payment-flows/applepay/applepay.js
> +export function isApplePayEligible({ serviceData } : IsEligibleOptions) : boolean {
Yeah, just to weigh in here; it's standard practice in this repo to test by:

- Treating the implementation as a black-box
- Writing tests which simulate user behavior (e.g. click on a button, fill out a form)
- Mocking out any external interfaces (e.g. network requests, window.ApplePay)
- Testing the public interface (e.g. were the right things passed to `window.xprops.onApprove`?)

This way the tests stay very decoupled from the implementation, and we can easily refactor the code without needing to change a bunch of unit tests at the same time.

Unit tests I think are totally fine for small reusable functions like `request` or `stringify` or whatnot. But ideally not for huge business cases like those in `payment-flows`.

For example:

- The PR manually calls `initApplePay`. But how can we be sure then that an actual click on the apple pay button will correctly call that function?
- The PR mocks out `approveApplePayPayment`. But then how do we have any confidence that function works when it is supposed to? It would be better to mock the http call itself, so we can validate that the right values were passed to the mutation.

2022-01-26 21:59 UTC, andyfen commented on .vscode/settings.json
> +{
can we just add it ? running `npm run flow-typed` won't update the editor config. you have to disable typescript plugin otherwise, this solves that.

2022-01-26 22:04 UTC, andyfen commented on src/payment-flows/applepay/applepay.js
> +export function isApplePayEligible({ serviceData } : IsEligibleOptions) : boolean {
we will have both unit tests and integration tests

2022-01-27 14:37 UTC, mnicpt commented on src/api/order.js
> +                    currencySymbol : string,
Gotcha!  Good catch!  `currencySymbol` should not be of type CURRENCY.  The symbol is just `$` and CURRENCY type is like `USD`.

2022-01-27 14:39 UTC, mnicpt commented on .vscode/settings.json
> +{
Let's leave this for another PR for other engineers to chime in on because we don't do this currently no in checkout components and any of their dependent repos.

2022-01-27 19:29 UTC, andyfen commented on src/payment-flows/applepay/applepay.js
> +export function isApplePayEligible({ serviceData } : IsEligibleOptions) : boolean {
> This way the tests stay very decoupled from the implementation, and we can easily refactor the code without needing to change a bunch of unit tests at the same time.
i would argue high unit test coverage would make it easier to refactor the code without breaking it, that's really the purpose of adding these.

2022-01-27 23:16 UTC, andyfen commented on src/payment-flows/applepay/applepay.js
> +export function isApplePayEligible({ serviceData } : IsEligibleOptions) : boolean {
@mnicpt  it is exporting it all at the bottom, i can just import that 
https://github.com/paypal/paypal-smart-payment-buttons/blob/master/src/payment-flows/applepay/applepay.js#L493-L500

2022-01-28 18:06 UTC, mnicpt commented on .vscode/settings.json
> +{
@andyfen Still needs to be removed.

2022-01-28 18:09 UTC, mnicpt commented on src/payment-flows/applepay/__tests__/initApplePaySession-no-shipping.test.js
> +    test('it should handle click and trigger sesison begin', async () => {
`session`

2022-01-28 18:09 UTC, mnicpt commented on src/payment-flows/applepay/__tests__/initApplePaySession-no-shipping-has-tax.test.js
> +    test('it should handle click and trigger sesison begin', async () => {
`session`

2022-01-28 18:11 UTC, mnicpt commented on src/payment-flows/applepay/__tests__/initApplePaySession-no-shipping-has-tax.test.js
> +                shippingAddress: {
Does `shippingAddress` get returned from `checkoutSession` if not provided?

2022-01-28 18:11 UTC, mnicpt commented on src/payment-flows/applepay/__tests__/initApplePaySession-no-shipping-has-tax.test.js
> +jest.mock('../../../api', () => ({
Maybe pull out mocks into separate folder for reuse?

2022-01-28 18:15 UTC, mnicpt commented on src/payment-flows/applepay/applepay.js
> +
Please remove spaces.

2022-01-28 18:21 UTC, mnicpt commented on src/payment-flows/applepay/utils.js
> +export function getSupportedNetworksFromIssuers(issuers : $ReadOnlyArray<string>) : $ReadOnlyArray<ApplePaySupportedNetworks> {
No need to make public.  This is tested already through public interface.  Please remove.

2022-01-28 18:21 UTC, mnicpt commented on src/payment-flows/applepay/utils.js
> +export function getShippingContactFromAddress(shippingAddress : ?ShippingAddress) : ApplePayPaymentContact {
No need to make public.  This is tested already through public interface.  Please remove.

2022-01-28 18:21 UTC, mnicpt commented on src/payment-flows/applepay/utils.js
> +export function getApplePayShippingMethods(shippingMethods : ?$ReadOnlyArray<ShippingMethod>) : $ReadOnlyArray<ApplePayShippingMethod> {
No need to make public.  This is tested already through public interface.  Please remove.

2022-01-28 18:22 UTC, mnicpt commented on src/payment-flows/applepay/utils.js
> +export function getMerchantCapabilities(supportedNetworks : $ReadOnlyArray<ApplePaySupportedNetworks>) : $ReadOnlyArray<ApplePayMerchantCapabilities> {
No need to make public.  This is tested already through public interface.  Please remove.

2022-01-28 18:54 UTC, andyfen commented on src/payment-flows/applepay/__tests__/initApplePaySession-no-shipping-has-tax.test.js
> +                shippingAddress: {
yes

2022-01-28 18:55 UTC, andyfen commented on src/payment-flows/applepay/__tests__/initApplePaySession-no-shipping-has-tax.test.js
> +jest.mock('../../../api', () => ({
you can't reference an external fixture inside a jest.mock

2022-01-28 18:56 UTC, andyfen commented on src/payment-flows/applepay/__tests__/initApplePaySession-no-shipping-has-tax.test.js
> +jest.mock('../../../api', () => ({
and each mock is a different checkoutSession response

2022-01-28 18:57 UTC, andyfen commented on src/payment-flows/applepay/__tests__/utils.test.js
> +/* @flow */
sorry mate, we want 100%

2022-01-28 19:16 UTC, andyfen commented on src/payment-flows/applepay/__tests__/initApplePaySession-no-shipping-has-tax.test.js
> +                shippingAddress: {
which may well be why your release has broken

2022-01-28 19:23 UTC, andyfen commented on src/payment-flows/applepay/__tests__/initApplePaySession-no-shipping-has-tax.test.js
> +                shippingAddress: {
everything is null
```
                "shippingAddress": {
                    "firstName": null,
                    "lastName": null,
                    "line1": null,
                    "line2": null,
                    "city": null,
                    "state": null,
                    "postalCode": null,
                    "country": null
                },
```

2022-01-28 19:53 UTC, andyfen commented on src/payment-flows/applepay/__tests__/initApplePaySession-no-shipping-has-tax.test.js
> +                shippingAddress: {
that looks like whats happened https://github.com/paypal/paypal-smart-payment-buttons/commit/3eeffad866f8752e75ddd4e06b5dcf785377816e
do you still think we shouldn't unit test ?

2022-01-31 19:11 UTC, andyfen commented on .vscode/settings.json
> +{
> we don't do this currently no in checkout components and any of their dependent repos.

here you go https://github.com/paypal/paypal-checkout-components/pull/1863

2022-01-31 19:52 UTC, andyfen commented on .vscode/settings.json
> +{
it tells you to do this in the plugin readme 
https://marketplace.visualstudio.com/items?itemName=flowtype.flow-for-vscode

2022-01-31 20:55 UTC, mnicpt commented on .vscode/settings.json
> +{
I'm guessing you're the only one I know of now dealing with this because you are coding with TypeScript and this is Flow.  We don't use TypeScript at this point in time.  You can disable for now.  I've spoken to many of my colleagues and we are in agreement to not include this nor will we allow it in checkout-components. For now, if you want to contribute to these repos, will need you to follow our guidance and recommendations for these repos.

2022-01-31 22:24 UTC, andyfen commented on .vscode/settings.json
> +{
is this not typescript ? https://github.com/paypal/paypal-js

you actually are actually seriously asking that people disable a plugin they use just so they can work on this repo.

2022-02-01 01:15 UTC, mnicpt commented on .vscode/settings.json
> +{
No. We are asking that you keep your private settings private and not part of the public repo. Thank you.

2022-02-02 01:43 UTC, closed without merging