[no merge] rework applepay
paypal/paypal-smart-payment-buttons pull request #437
Opened 2022-07-06 18:14 UTC by andyfen

```
paypal.Buttons({
  style: {
    label: "pay",
  },
  paymentRequest: {
    applepay: {
      requiredBillingContactFields: [
        "postalAddress"
      ],
      requiredShippingContactFields: [
        "postalAddress",
        "name",
        "phone",
        "email",
      ],
    },
  },
  onCancle() {
    logResponse("onCancel called", {});
  },
  createOrder(data, actions) {
    return actions.order.create(order);
  },
});

```

2022-07-20 01:21 UTC, mnicpt requested changes
Has this prop been approved? Why is it needed as a prop?

2022-07-26 16:06 UTC, wsbrunson approved these changes

2022-07-26 17:18 UTC, gregjopa commented on src/api/config.js
> +        headers:   {
Can we remove the unused `headers` part?
```suggestion
```

2022-07-26 18:38 UTC, andyfen commented on src/api/config.js
> +        headers:   {
gone

2022-07-26 21:30 UTC, gregjopa approved these changes

2022-07-28 13:54 UTC, sioked commented
@andyfen can you work on increasing the coverage on this as well? I think you should be able to squash & merge as is, but I'd love to have the coverage a bit higher here.

2022-07-28 14:25 UTC, gregjopa commented
> @andyfen can you work on increasing the coverage on this as well? I think you should be able to squash & merge as is, but I'd love to have the coverage a bit higher here.

I agree about improving coverage. Let's tackle that in a future PR. Andy is OOO today so I'm going to merge this as is.

2022-07-28 14:28 UTC, merged