PPoF
paypal/paypal-smart-payment-buttons pull request #511
Opened 2022-12-02 22:22 UTC by nbierdeman

### Description

Herein lies the changes necessary to facilitate the PPoF flow. The most noteworthy change is the introduction of a new callback, `onSmartWalletEligible`. When called, it will initialize a "third" render of the PayPal button with the smart wallet instrument label(s) and logo displayed. 🔥 

### Dependent Changes

These changes need to be released to production first:

- https://github.com/paypal/paypal-checkout-components/pull/2038
- https://github.com/paypal/paypal-sdk-constants/pull/113

2022-12-02 22:25 UTC, gregjopa commented on src/api/auth.js
> +export function exchangeAccessTokenForAuthCode(buyerAccessToken : string | ZalgoPromise<string>) : ZalgoPromise<string> {
Can you share why this `ZalgoPromise<string>` change is needed for the buyerAccessToken input?

2022-12-02 23:30 UTC, jshawl reviewed
LGTM I've not yet run this locally but wanted to get my comments in early. all non-blocking

2022-12-02 23:30 UTC, jshawl commented on src/button/button.js
> +    featureFlags: FeatureFlags,
this is the smallest thing but the other properties have a space around `:`

2022-12-02 23:30 UTC, jshawl commented on src/button/button.js
> +                    [FPTI_KEY.STATE]:      FPTI_STATE.BUTTON,
future refactor idea: we could create a generic `onSpbErrorHandler` and add them to `.catch` for `initiatePayment` and `initiateMenu` functions

2022-12-02 23:30 UTC, jshawl commented on src/button/props.js
> +    featureFlags: FeatureFlags,
same comment about space around `:`

2022-12-02 23:30 UTC, jshawl commented on src/payment-flows/checkout.js
> +                const { country, lang } = smartWalletLocale || locale;
I think `smartWalletLocale` is already destructured to `locale` in the function definition parameters, right?

so this should just be

```
const { country, lang } = locale;
```

2022-12-02 23:30 UTC, jshawl commented on src/payment-flows/checkout.js
> +                }
what do you think about:

```
const access_token = accessToken || buyerAccessToken || "";
```

I think that's the same... 🤔

2022-12-02 23:30 UTC, jshawl commented on src/payment-flows/wallet-capture.js
> +        if(getBuyerAccessToken()) {
I wasn't sure if the function call here was intentional - it looks ok per https://github.com/paypal/paypal-smart-payment-buttons/blob/387e98061c5bfc522d521ed7985839058e7c8d47/src/lib/session.js#L38-L41 but I wonder if it would be clearer to future readers to:

```js
const buyerAccessToken = getBuyerAccessToken()
if(buyerAccessToken){
  // ...
}
```

2022-12-02 23:30 UTC, jshawl commented on src/payment-flows/wallet-capture.js
> +            const buyerAccessToken = (enableOrdersApprovalSmartWallet && getBuyerAccessToken()) || getInstrument(smartWallet, fundingSource, instrumentID).accessToken;
in what situations would `getInstrument().accessToken` be different from `getBuyerAccessToken`? 

might be worth a comment about why the buyer access token changes

2022-12-02 23:30 UTC, jshawl commented on src/payment-flows/wallet-capture.js
> +                                if(enableOrdersApprovalSmartWallet && getBuyerAccessToken()) {
same comment here about setting the invocation to a variable and then using the variable in the conditional

2022-12-02 23:30 UTC, jshawl commented on src/props/props.js
> +    featureFlags: FeatureFlags,
same comment about space around `:` 🙈

2022-12-02 23:30 UTC, jshawl commented on src/constants.js
> +    ELIGIBILITY_CHECK: ('eligibility_check' : 'eligibility_check')
is this a flow thing? I've not seen `('a' : 'b')` before I think...

2022-12-05 16:26 UTC, wsbrunson reviewed
we should talk about where we can add tests in this repo for some of the most important new additions

2022-12-05 20:44 UTC, nbierdeman commented on src/api/auth.js
> +export function exchangeAccessTokenForAuthCode(buyerAccessToken : string | ZalgoPromise<string>) : ZalgoPromise<string> {
I must've left this in here on accident. I just removed it. Thanks for the catch. 👍

2022-12-05 21:09 UTC, wsbrunson commented on src/button/button.js
> +    featureFlags: FeatureFlags,
i would ignore any style stuff, we are gonna run `prettier` over this whole repo in the new year

2022-12-05 21:14 UTC, nbierdeman commented on src/button/props.js
> +    featureFlags: FeatureFlags,
Sounds like we're gonna use prettier in the new year to standardize styles.

2022-12-05 21:15 UTC, nbierdeman commented on src/props/props.js
> +    featureFlags: FeatureFlags,
Same comment as above re: a prettier new year. 😁

2022-12-05 21:24 UTC, nbierdeman commented on src/constants.js
> +    ELIGIBILITY_CHECK: ('eligibility_check' : 'eligibility_check')
Yes, it's a kind of flow [type casting](https://flow.org/en/docs/types/casting/).

![Screen Shot 2022-12-05 at 2 21 46 PM](https://user-images.githubusercontent.com/20399044/205745464-b530c6e7-0f1f-4e4e-bc7b-13785502d315.png)

2022-12-05 22:05 UTC, nbierdeman commented on src/payment-flows/checkout.js
> +                const { country, lang } = smartWalletLocale || locale;
`locale` is a required `onSmartWalletEligible` parameter name (I believe its part of the billing team interface), so it gets renamed to `smartWalletLocale` to avoid a naming conflict with `initCheckout` -> `props` -> `locale`. If `smartWalletLocale` is falsey, then `country` and `lang` get destructured from `initCheckout` -> `props` -> `locale`.

2022-12-05 22:37 UTC, nbierdeman commented on src/payment-flows/checkout.js
> +                const { country, lang } = smartWalletLocale || locale;
Here's the error I get if I do either `const { country, lang } = locale` or `const { country, lang } = locale || locale` and `onSmartWalletEligible` is called without passing in `locale`. I think this is why I renamed it `smartWalletLocale`. It's basically saying, get `country` and `lang` from `onSmartWalletEligible` -> `smartWalletLocale`, or else fall back to `initCheckout` -> `locale`. Does that make sense? I'm really having to try to remember the `why`, but I think that's it. 😆 

![Screen Shot 2022-12-05 at 3 24 48 PM](https://user-images.githubusercontent.com/20399044/205757341-176377e2-355d-49fd-b25d-0f93d7a49310.png)

2022-12-05 22:45 UTC, nbierdeman commented on src/payment-flows/wallet-capture.js
> +            const buyerAccessToken = (enableOrdersApprovalSmartWallet && getBuyerAccessToken()) || getInstrument(smartWallet, fundingSource, instrumentID).accessToken;
Good question! @ravishekhar, do you know the difference between `getInstrument().accessToken` and `getBuyerAccessToken()`?

2022-12-05 23:06 UTC, nbierdeman commented on src/payment-flows/checkout.js
> +                }
Yeah, nice. Thx!

2022-12-06 00:24 UTC, ravishekhar requested changes

2022-12-06 16:26 UTC, nbierdeman commented on src/props/props.js
> +export type XOnSmartWalletEligibleDataType = {|
I wasn't getting any type errors without `locale`, but went ahead and added it.

2022-12-06 16:55 UTC, nbierdeman commented on src/button/logger.js
> +        const getFI_ID = function () : string | void {
That's a much better name. 😁

2022-12-06 18:23 UTC, nbierdeman commented on src/types.js
> +    onSmartWalletEligible? : ({| accessToken : string, eligibilityReason : string, locale? : LocaleType, orderID : string |}) => ZalgoPromise<{| smartWalletRendered : boolean, buyerIntent : string |}
I went ahead and pushed this change.

2022-12-07 22:48 UTC, gregjopa commented on src/payment-flows/checkout.js
> +                if (window.innerWidth < 300 || buyerIntent === BUYER_INTENT.PAY_WITH_DIFFERENT_FUNDING_SHIPPING || buyerIntent === BUYER_INTENT.PAY_WITH_DIFFERENT_ACCOUNT) {
For readability, can we assign `300` to a variable? Just like: https://github.com/paypal/paypal-smart-payment-buttons/blob/0317e4358a879559c99966d3eb61f88ac90e3e58/src/payment-flows/vault-capture.js#L19

2022-12-07 23:15 UTC, nbierdeman commented on src/payment-flows/checkout.js
> +                createOrder().then(walletOrderID => {
I believe this should be a fire and forget operation, where we initialize the third render of the button and notify the caller of `onSmartWalletEligible` of that. I'll circle back if I hear differently after discussing it with @ravishekhar.

2022-12-07 23:19 UTC, ravishekhar commented on src/payment-flows/checkout.js
> +                createOrder().then(walletOrderID => {
At this point createOrder will return a memoized orderID. So this will always resolve.
We can take up an optimization here though, to return from finally block of this promise chain before reloading the buttons. Should take it up as a separate PR?

2022-12-07 23:29 UTC, gregjopa approved these changes

2022-12-08 19:38 UTC, sioked commented on src/button/button.js
> +        setBuyerAccessToken(buyerAccessToken);
cc @elizabethmv - I know we changed some logic on this recently, want to get your eyes here as well

2022-12-08 22:24 UTC, nbierdeman commented on src/payment-flows/checkout.js
> +                createOrder().then(walletOrderID => {
It will be called post login by checkout UI apps after determining eligibility.

2022-12-09 21:34 UTC, elizabethmv commented on src/button/button.js
> +        setBuyerAccessToken(buyerAccessToken);
Sharing an update, we were able to discuss this a bit more in slack. These buyer access token cases should be specific for third render with ppof

2022-12-09 21:38 UTC, elizabethmv commented on src/button/logger.js
> +            if (wallet?.paypal?.instruments[0]?.secondaryInstruments && wallet.paypal.instruments[0].instrumentID) {
Is the optional chaining missing in the second part of the condition?

2022-12-09 21:45 UTC, nbierdeman commented on src/button/logger.js
> +            if (wallet?.paypal?.instruments[0]?.secondaryInstruments && wallet.paypal.instruments[0].instrumentID) {
It wasn't necessary to repeat the optional chaining for the same object and properties after `&&`, since it'll short circuit upon evaluating any falsey values in the first condition.

2022-12-09 21:52 UTC, elizabethmv approved these changes

2022-12-09 22:18 UTC, ravishekhar approved these changes

2022-12-13 21:42 UTC, merged