feat: hosted card fields handle a provided action
paypal/paypal-smart-payment-buttons pull request #532
Opened 2023-01-09 18:39 UTC by thebastedo

### Description

### Why are we making these changes? Include references to any related Jira tasks or GitHub Issues

### Reproduction Steps (if applicable)

### Screenshots (if applicable)

### Dependent Changes (if applicable)

### Groups who should review (if applicable)

❤️  Thank you!

2023-01-18 17:50 UTC, cgdibble commented on src/card/interface.js
> +  await updateVaultSetupToken({ vaultSetupToken, lowScopedAccessToken, paymentSourceDetails });
Ahh, this clicked weirdly late, but we're updating the _same_ token with new data and thus just return the original vault token once it is updated with the paymentSourceDetails. 👍

2023-01-18 18:48 UTC, wsbrunson approved these changes

2023-01-19 00:06 UTC, cgdibble requested changes
Some changes to expand testing to cover error scenarios/sad paths as well, plus `vaultPaymentSource` not being resolved in submit.

2023-01-19 00:06 UTC, cgdibble commented on tests/card/interface.test.js
> +  describe("updateVaultSetupToken", () => {
Can we include a test that specifies the failure scenario? How do we expect/assert `updateVaultSetupToken` to handle failures?

2023-01-19 00:07 UTC, cgdibble commented on src/card/props.js
> +      ...(action?.props?.action && { action: parent.props.action })
This had me wondering from before, but why `parent.props.action`? What is that in this context and why?

2023-01-19 15:35 UTC, wsbrunson commented on src/card/props.js
> +      ...(action?.props?.action && { action: parent.props.action })
@cgdibble we chatted about this in the planning meeting, we are about to write a ticket about why. Basically, the parent component uses the same initialization method as the children. When we get the card props here, we are actually getting them from the child components (NameField, NumberField, etc) instead of the parent CardField component.

We have a plan to stop doing this though and then this can be `props.action` instead of `parent.props.action` but we didn't want to stop this work to do it

2023-01-19 20:06 UTC, thebastedo commented on src/card/interface.js
> +          vaultPaymentSource({
I couldn't get that to work with flow. the major challenge here from a flow perspective if that whole function does not have a consistent return pattern, as further down in the logic we have different places where we return void. As well is there something upstream waiting for this that we need to return the async promise?

2023-01-19 20:21 UTC, thebastedo commented on src/card/interface.js
>    // TODO: For next ticket, take these card props and act on them based on action flow or not
Good catch, I cleaned those out but musta snuck back in in one of my merges

2023-01-19 23:13 UTC, cgdibble commented on src/card/interface.js
> +          vaultPaymentSource({
Honestly Zalgo just borks the ease of use around async here and I don't care what it says haha

I guess returning the async call was my hope/attempt to try and keep it consistent. Having `vaultPaymentSource` resolve undefined/void, and returning that seemed the best way to do it. 

> As well is there something upstream waiting for this that we need to return the async promise?

Good question, I'll need to take a look locally for ease of navigation, but I think we can at least determine that the happy paths are currently doing so in here already. You're right that the `onApprove` is the thing the merchant waits on, but we should be consistent within this submit function.

> I couldn't get that to work with flow

What about the flow broke when returning here?

2023-01-19 23:52 UTC, thebastedo commented on src/card/interface.js
> +          vaultPaymentSource({
> I guess returning the async call was my hope/attempt to try and keep it consistent.

I agree, I'm revisiting this at the moment I'll see if I can't be smarter than flow here.

> What about the flow broke when returning here?

Mainly was the fact that at the end we return `onApprove`, which is merchant provided so we can't expect it to return a `ZalgoPromise` which is the expected return. I think I just need to figure out how to set the return as `Promise<void> | ZalgoPromise<void>`

2023-01-25 21:43 UTC, thebastedo commented on tests/card/interface.test.js
> +  describe("updateVaultSetupToken", () => {
Errors should bubble up the promise chain and should now be testing this in the `submitCardFields` tests

2023-01-25 21:44 UTC, thebastedo commented on tests/card/interface.test.js
> +  describe("vaultPaymentSource", () => {
Should be testing for those now in the `submitCardFields` unit tests

2023-01-25 22:29 UTC, jplukarski approved these changes

2023-01-25 22:33 UTC, thebastedo commented on src/card/interface.js
> +          vaultPaymentSource({
I don't know exactly what I changed but I think this should be addressed, take a look here https://github.com/paypal/paypal-smart-payment-buttons/blob/a75d8ec50ba5639dfa7bed0399983e9e9a0681af/src/card/interface/submitCardFields.js#L67

2023-01-26 00:07 UTC, cgdibble commented on tests/card/interface/gql.test.js
> +    expect(true).toBe(true);
Just noting a TODO so this doesn't fly under the radar.

2023-01-26 00:09 UTC, cgdibble commented on tests/card/interface/submitCardFields.test.js
> +        type: 'save',
FWIW I believe it was decided that this is capitalized. Probably worth trying to be consistent for test expectations. Do we have that defined somewhere we can even reference?

2023-01-26 00:11 UTC, cgdibble commented on tests/card/interface/submitCardFields.test.js
> +  it('should throw an error when given an unsuported action', async () => {
```suggestion
  it('should throw an error when given an unsupported action', async () => {
```

2023-01-26 00:16 UTC, cgdibble commented on tests/card/interface/submitCardFields.test.js
> +    expect(mockInfo).toHaveBeenCalledOnce();
Does this logger represent analytics? I want to clarify because IMO testing against general logs is flaky and not a good idea, but if this is an analytics call and thus inherently more stable as a testable value, then that works for me!

2023-01-26 00:18 UTC, cgdibble commented on tests/card/interface/submitCardFields.test.js
> +  it('should tokenize', async () => {
What if we organized these tests in to describes for "standalone vault" and "checkout" or something? It might help organize them better and keep mocks/etc. scoped more cleanly

2023-01-26 00:20 UTC, cgdibble commented on tests/card/interface/updateVaultSetupToken.test.js
> +describe("card/interface/updateVaultSetupToken", () => {
Can we be consistent with the top-level describes in each test file? Personally I think just the function name
 under test is the way to go, but open to others

2023-01-26 00:21 UTC, cgdibble commented on tests/card/interface/updateVaultSetupToken.test.js
> +  it("should call request with the correct", async () => {
What happens if this call to the API fails? What is our expectation here? Can we provide a test + assertion for this?

2023-01-26 00:22 UTC, cgdibble commented on tests/card/interface/vaultPaymentSource.test.js
> +  it("should call the provided functions", async () => {
Can we get assertions/tests around the failure cases, too?

2023-01-26 17:15 UTC, wsbrunson approved these changes

2023-01-26 17:15 UTC, wsbrunson commented on src/card/interface/hasCardFields.js
> +  return false;
```suggestion
  return cardFrame || (cardNumberFrame && cardCVVFrame && cardExpiryFrame)
```

2023-01-26 17:35 UTC, wsbrunson commented on src/card/interface/updateVaultSetupToken.js
> +    url: vaultUrl,
```suggestion
  return request({
    method: 'post',
    url: `/v3/vault/setup-tokens/${vaultSetupToken}/update`,
```

2023-01-26 18:45 UTC, thebastedo commented on tests/card/interface/vaultPaymentSource.test.js
> +  it("should call the provided functions", async () => {
Those errors should bubble up through the promise chain, those get tested by the catch and error handling inside the `submitCardFields` function

2023-01-26 18:45 UTC, thebastedo commented on tests/card/interface/updateVaultSetupToken.test.js
> +  it("should call request with the correct", async () => {
this function isn't concerned with handling that failure case. that promise failure will bubble up and get caught in the `submitCardFields` function

2023-01-31 16:21 UTC, bywood commented on src/card/interface/updateVaultSetupToken.js
> +import { getPayPalDomain } from "@paypal/sdk-client/src";
`getPayPalDomain` doesn't appear to be used.

2023-01-31 16:21 UTC, bywood commented on src/card/interface/submitCardFields.js
> +            throw error;
I'm not as familiar with `ZalgoPromise`. Is this thrown error catchable? Who should be catching it?

2023-02-01 19:18 UTC, elizabethmv approved these changes

2023-02-01 20:03 UTC, merged