HCF Vault with Purchase documentation
paypal/paypal-smart-payment-buttons pull request #534
Opened 2023-01-11 22:33 UTC by wickerpopstar

### Description
Initial docs for Vault with Purchase functionality with new HCF. General flow outlined, details for specific card types coming with those specific tickets. No functionality changes required for Vault with Purchase for HCF.

### Why are we making these changes? Include references to any related Jira tasks or GitHub Issues

[DTNOR-551](https://paypal.atlassian.net/browse/DTNOR-551)

@paypal/js-sdk-maintainers 

❤️  Thank you!

2023-01-12 16:32 UTC, wsbrunson approved these changes

2023-01-12 17:18 UTC, bywood commented on src/card/docs/Vaulting/README.md
> +Vaulting with MasterCard uses an asynchronous process. Instead of a vault `id` being returned, a `setupToken` is returned. More details TBD.
`setupToken` -> `setup_token`

2023-01-12 17:20 UTC, bywood commented on src/card/docs/Vaulting/README.md
> +Vaulting with American Express requires an additional field `partner` to be added to the `POST /create-order` payload with a value of `true`. More details TBD.
The `partner` field is specific to `xotestbednodeweb`. For American Express cards, my understanding is that the merchant needs to be subscribed to their OptBlue feature.

2023-01-12 17:29 UTC, bywood commented on src/card/docs/Vaulting/README.md
> +2. The order is successfully created and the `orderId` is returned along with vaulting details such as the `id` of the vaulted payment method.
I think the vaulting details are returned in the capture call, not the create order call.

2023-01-12 18:00 UTC, elizabethmv commented on src/card/docs/Vaulting/README.md
> +
For HCF vault with purchase using orders V2 we want to avoid using the vault param. This will enabled the auto vaulting flow and override the vault attributes in the order
```suggestion
```

2023-01-12 20:59 UTC, wickerpopstar commented on src/card/docs/Vaulting/README.md
> +1. Calling `POST /create-order` creates the order specifying the card as payment method, and indicates vaulting for the specified customer.
Definitely—my understanding was that the testbed was effectively emulating the perspective of a merchant using SPB. I did a pass and converted some of the routes to the general PPaaS Order API routes instead of the proxies set up in the TB, but I clearly missed some. Is that the correct approach to us the Order API routes or do you think it would be better to just refer to them as the generic work being done?

2023-01-12 21:00 UTC, wickerpopstar commented on src/card/docs/Vaulting/README.md
> +
Thanks, I did not know this. This note was going off of the early approach we were using in hard coding on the TB, so that makes sense.

2023-01-12 21:07 UTC, wickerpopstar commented on src/card/docs/Vaulting/README.md
> +Vaulting with American Express requires an additional field `partner` to be added to the `POST /create-order` payload with a value of `true`. More details TBD.
It looks to me like `partner` does still get passed in the body of the `/checkout/orders` and used as part of the auth token that gets generated for that call. I thought the `/checkout/orders` route in the Orders API was the same route any merchant would need to use, is that not the case?

2023-01-12 21:10 UTC, wickerpopstar commented on src/card/docs/Vaulting/README.md
> +2. The order is successfully created and the `orderId` is returned along with vaulting details such as the `id` of the vaulted payment method.
I thought I had seen them returned in both. The PPaaS API reference has them in the response for both the `POST /checkout/orders` call and the `POST /checkout/orders/{id}/capture` calls.

2023-01-13 16:09 UTC, bywood commented on src/card/docs/Vaulting/README.md
> +2. The order is successfully created and the `orderId` is returned along with vaulting details such as the `id` of the vaulted payment method.
Hmm...I don't recall seeing it in the `orders` response. I've only seen it in the `capture` response.

2023-01-13 16:20 UTC, bywood commented on src/card/docs/Vaulting/README.md
> +1. Calling `POST /create-order` creates the order specifying the card as payment method, and indicates vaulting for the specified customer.
The test bed does emulate the perspective of the merchant, but both the client and server side of the merchant's app. This only covers the client side integrating with the test bed's server side, which would also be owned by the merchant.

2023-01-13 16:35 UTC, bywood commented on src/card/docs/Vaulting/README.md
> +Vaulting with American Express requires an additional field `partner` to be added to the `POST /create-order` payload with a value of `true`. More details TBD.
My understanding is that `partner` is a construct of the `xotestbednodeweb` app to allow us to switch between different client IDs and secrets. For example: https://github.paypal.com/Checkout-R/xotestbednodeweb/blob/develop/lib/Request.js#L75-L78

So `xotestbednodeweb`'s `/xo-integrations/api/create-order` uses it to get the desired client ID and secret needed to create the access token used by the actual call to  PayPal's `/v2/checkout/orders`.

2023-01-18 17:57 UTC, wickerpopstar commented on src/card/docs/Vaulting/README.md
> +2. The order is successfully created and the `orderId` is returned along with vaulting details such as the `id` of the vaulted payment method.
You're definitely right about this. I must have been confusing the documentation with our tests.

2023-01-18 19:48 UTC, bywood requested changes

2023-01-18 19:48 UTC, bywood commented on src/card/docs/Vaulting/README.md
> +3. The order is successfully created and the `orderId` is returned along with vaulting details such as the `id` of the vaulted payment method.
The vaulting details are not returned in the `/checkout/orders` response. So I recommend removing: "along with vaulting details such as the `id` of the vaulted payment method".

2023-01-18 19:48 UTC, bywood commented on src/card/docs/Vaulting/README.md
> +2. API calls `POST /checkout/orders` with vault specific field.
Should we specify the full path? `/v2/checkout/orders`

2023-01-18 19:48 UTC, bywood commented on src/card/docs/Vaulting/README.md
> +5. API calls `POST /checkout/capture`, vault details are returned and processing continues as usual.
Path should be: `/v2/checkout/orders/${orderId}/capture`

2023-01-18 19:51 UTC, wickerpopstar commented on src/card/docs/Vaulting/README.md
> +2. API calls `POST /checkout/orders` with vault specific field.
I was considering that. I was originally thinking to keep it more generic, but I suppose we're really only building this for latest functionality. I'll add it in now, and it can be removed in the future if need be.

2023-01-18 19:56 UTC, bywood approved these changes

2023-01-20 20:19 UTC, wsbrunson approved these changes

2023-01-20 20:19 UTC, wsbrunson commented on src/card/docs/Vaulting/README.md
> +  },
```suggestion
  }
```

2023-01-25 20:39 UTC, merged