Standalone Vault Pt 3
paypal/paypal-smart-payment-buttons pull request #543
Opened 2023-02-08 19:56 UTC by wsbrunson

2023-02-08 23:12 UTC, bywood requested changes

2023-02-08 23:12 UTC, bywood commented on src/card/interface/submitCardFields.js
> +  const month = parseInt(dateArray[0] | "", 10);
Was this meant to be `dateArray[0] || ""`. However, `parseInt("", 10)` would return `NaN`, which would create an invalid date further down.

2023-02-08 23:12 UTC, bywood commented on src/card/interface/submitCardFields.js
> +  const year = parseInt(dateArray[1] | "", 10);
Same as above.

2023-02-08 23:53 UTC, cgdibble commented on src/api/vault.js
> +export type PaymentSourceInput = {|
I find it hard to believe this isn't defined somewhere already that could be re-used...but hell either way it looks good.

2023-02-08 23:53 UTC, cgdibble commented on src/api/vault.js
> +      vaultSetupToken,
Given this is Standalone-specific, we could name this local var to be more explicitly `emptyVaultSetupToken`? Though, tokens are so complex maybe calling it empty is a potentially confusing assumption ha

2023-02-08 23:53 UTC, cgdibble commented on src/card/interface/vault.js
> +    return getVaultSetupToken({
I'm a little confused on this ordering now. What is `getVaultSetupToken` doing? I thought standalone just had to make the one API call and it was the step done in `updateVaultSetupToken`.

2023-02-09 13:56 UTC, wsbrunson commented on src/card/interface/submitCardFields.js
> +  const month = parseInt(dateArray[0] | "", 10);
I'm going to write tests for this function and I can experiment with using strings vs numbers. I think the `Date` api expects `Date(number, number, number)` if you are going that route instead of passing a date string but i'm not sure

2023-02-09 13:56 UTC, wsbrunson commented on src/api/vault.js
> +export type PaymentSourceInput = {|
you and me both brother

2023-02-09 13:57 UTC, wsbrunson commented on src/api/vault.js
> +export type PaymentSourceInput = {|
@gregjopa and I keep talking about putting all of our Types (api request/response, general sdk types) in a central location. Not sure what that package is, most likely it will be TypeScript though

2023-02-09 13:57 UTC, wsbrunson commented on src/api/vault.js
> +      vaultSetupToken,
yeah at this point it is a `string` so while we know its empty because it was just created, it doesn't change as we go through the flow, its always the same `string`

2023-02-09 14:03 UTC, wsbrunson commented on src/card/interface/vault.js
> +    return getVaultSetupToken({
I think we will understand this more when we do the PayPal wallet. For the PayPal Wallet, we would get the contingency when the token is created, we'd need to do a `get` to check for said contingency. I think with Cards, we don't get a contingency until we update it with the card details. At that point, we'd need to display the 3DS screen to approve.

I think if this ends up being the case, we could have separate functions for vaulting wallets vs cards

2023-02-09 15:12 UTC, elizabethmv commented on src/card/interface/vault.js
> +  idToken: string,
Should all of these `idToken` be `userIDToken`?

2023-02-09 15:12 UTC, elizabethmv commented on src/card/interface/vault.js
> +      partnerAttributionID: "",
Should we take this `partnerAttributionID` off until we know if we need it?

2023-02-09 16:05 UTC, wsbrunson commented on src/card/interface/submitCardFields.js
> +const convertMMYYToPaymentSourceDate = (dateString = "") => {
oof i did not know that

2023-02-09 16:06 UTC, wsbrunson commented on src/card/interface/submitCardFields.js
> +  const month = parseInt(dateArray[0] | "", 10);
oh wait i see what you are saying now. we should just throw an error if we don't have a date string here

2023-02-09 16:20 UTC, bywood commented on src/card/interface/submitCardFields.js
> +  const month = parseInt(dateArray[0] | "", 10);
Yeah, if a thrown error would be handled correctly, then I think you could just do something like:
```js
  const month = parseInt(dateArray[0], 10);
  if (isNaN(month)) {
    // throw some error
  }
```

2023-02-09 20:23 UTC, cgdibble commented on src/api/vault.js
> +      vaultSetupToken,
Yeah that's a good perspective, I'm for it staying for sure. That's a great example of the `empty` verbiage being confusing because I was meaning the token itself doesn't have an associated payment source. But, yeah, carry on bad suggestion is bad lol

2023-02-09 20:25 UTC, cgdibble commented on src/card/interface/vault.js
> +    return getVaultSetupToken({
I'm confused more then...what's the new(ish) need of `getVaultSetupToken`? We get the token from the merchant via `createVaultSetupToken`, so what is `getVaultSetupToken` doing against the API and why?

2023-02-09 20:44 UTC, wsbrunson commented on src/api/vault.js
> +      vaultSetupToken,
not a bad suggestion at all! we are all continuously updating our mental models about what all this means

2023-02-13 20:05 UTC, cgdibble commented on src/card/props.js
> -  "intent",
Does `intent` have a role in this now? Something might well have changed, but wanna make sure so my understanding stays up to date. I'm adding these disallowed props to the docs now.

2023-02-13 20:11 UTC, cgdibble commented on src/card/props.js
> -  "intent",
Resolved offline. To try and paraphrase, intent wouldn't even come in from this means anyway, but we at least can and want to scope the disallowed list to callbacks and things the merchant passes directly to CardFields.

2023-02-14 14:47 UTC, wsbrunson commented on src/card/interface/vault.js
> +    return getVaultSetupToken({
Charlie and I talked about this in a meeting, for some vault cases we have to do a GET on the id token to check for contingencies. it's possible this will go away though once we better understand vaulting for cards and wallets

2023-02-14 14:48 UTC, wsbrunson commented on src/card/interface/submitCardFields.js
> +  const month = parseInt(dateArray[0] | "", 10);
ended up getting rid of this completely

2023-02-22 16:40 UTC, jplukarski approved these changes

2023-02-22 16:55 UTC, elizabethmv approved these changes
Some minor comments. Awesome work!

2023-02-22 16:55 UTC, elizabethmv commented on src/card/interface/index.js
> +export * from './standalone-vault';
Non blocking, `vault-without-purchase` might be even more clear on the flow

2023-02-22 16:55 UTC, elizabethmv commented on src/card/props.js
>   * When CardFields is used with an Action, the required properties change. This is for validating the arguments in that use-case.
Missing an update in this comment I think? Action -> Save

2023-02-22 16:55 UTC, elizabethmv commented on src/card/interface/standalone-vault.js
> +  // need to add error cases with fpti events for each .then
Bumping a reminder here for a follow up PR to check on the token statuses, etc.

2023-02-22 18:42 UTC, wsbrunson commented on src/card/interface/standalone-vault.js
> +  // need to add error cases with fpti events for each .then
yeah i should turn this into a jira ticket

2023-02-22 18:52 UTC, merged