[DTPPSDK-1246]add disable-set-cookie query string
paypal/paypal-smart-payment-buttons pull request #624
Opened 2023-06-22 22:26 UTC by xuanwan05

### Description
https://paypal.atlassian.net/browse/DTPPSDK-1246
Update logger call in SPB to conditionally add disable-set-cookie query string

### Why are we making these changes? Include references to any related Jira tasks or GitHub Issues

### Reproduction Steps (if applicable)

### Screenshots (if applicable)
<img width="1590" alt="Screenshot 2023-06-22 at 5 02 17 PM" src="https://github.com/paypal/paypal-smart-payment-buttons/assets/31012905/62773632-4bf4-42d3-8a84-c7f44beff71c">
### Dependent Changes (if applicable)

### Groups who should review (if applicable)

❤️  Thank you!

2023-06-22 22:59 UTC, spencersablan approved these changes
Looks great @xuanwan05! 👏

2023-06-22 23:28 UTC, spencersablan requested changes

2023-06-22 23:28 UTC, spencersablan commented on src/lib/logger.js
> +  const { disableSetCookie } = window.xprops;
```suggestion
  const { disableSetCookie = false} = Object(window.xprops);
```
@xuanwan05 actually, it looks like a few of our tests are failing due to `disableSetCookie` being undefined. 😅   I feel like it would be good to give this a default value anyway.  

We also may have to take into account the case where `window.xprops` is undefined.. I don't _think_ this will happen in real life, but its what's happening in the tests & its better to be safe than sorry.  😄   So that's why I proposed wrapping `window.xprops` in `Object()`.

2023-06-23 22:26 UTC, spencersablan approved these changes

2023-06-28 16:41 UTC, gregjopa commented on src/lib/logger.js
> +  const { disableSetCookie = false } = Object(window.xprops);
Ignore my comment above. We call this `getLogger()` call many times throughout the code base. Let's solve for this need here inside the `getLogger()` function.

Instead of `Object(window.xprops)`, can we be more strict with our type checking on window? Maybe something like

```js
let loggerUrl = LOGGER_URL;

if (window && typeof window.xprops === "object" && window.xprops.disableSetCookie) {
   loggerUrl = `${LOGGER_URL}?${disableSetCookieQuery}`; 
}

return inlineMemoize(getLogger, () =>
    Logger({
        url: loggerUrl,
        enableSendBeacon: true,
    })
)  
```

2023-06-29 14:52 UTC, merged