create new access token
paypal/paypal-smart-payment-buttons pull request #686
Opened 2023-09-25 17:05 UTC by xuanwan05

### Description

### Why are we making these changes? Include references to any related Jira tasks or GitHub Issues

### Reproduction Steps (if applicable)

### Screenshots (if applicable)

### Dependent Changes (if applicable)

### Groups who should review (if applicable)

❤️  Thank you!

2023-09-25 19:56 UTC, ravishekhar requested changes

2023-09-25 19:56 UTC, ravishekhar commented on src/api/auth.js
> +        }).then(noop).catch(err => {
We need to return the new value from returned from Graphql API to the callers.

2023-09-25 19:56 UTC, ravishekhar commented on src/props/onApprove.js
> +export const createNewAccessToken = async({ orderID, facilitatorAccessToken, buyerAccessToken }) : ?string  => {
This seems redundant method. Do we really need this abstraction? Can we use `upgradeFacilitatorAccessTokenWithIgnoreCache(...)` directly in below callbacks?

2023-09-25 19:56 UTC, ravishekhar commented on src/api/auth.js
> +export function upgradeFacilitatorAccessTokenWithIgnoreCache(facilitatorAccessToken : string, { buyerAccessToken, orderID } : {| buyerAccessToken : string, orderID : string |}) : ZalgoPromise<void> {
Lets keep a flat params for this method siganture as all params for mandatory for this. 
```suggestion
export function upgradeFacilitatorAccessTokenWithIgnoreCache(facilitatorAccessToken : string, buyerAccessToken : string, orderID : string) : ZalgoPromise<void> {
```

2023-09-25 19:56 UTC, ravishekhar commented on src/props/onApprove.js
> +                console.error("Cannot create new buyer access token");
Since we would update upgradeFacilitatorAccessTokenWithIgnoreCache(...) to not throw any errors. We can avoid this try catch block.

2023-09-25 19:56 UTC, ravishekhar commented on src/props/onApprove.js
> +                throw new Error("Cannot create new buyer access token");
Since we would update upgradeFacilitatorAccessTokenWithIgnoreCache(...) to not throw any errors. We can avoid this try catch block.

2023-09-25 19:56 UTC, ravishekhar commented on src/props/onApprove.js
> +                throw new Error("Cannot create new buyer access token");
Since we would update upgradeFacilitatorAccessTokenWithIgnoreCache(...) to not throw any errors. We can avoid this try catch block.

2023-09-25 19:56 UTC, ravishekhar commented on src/props/onApprove.js
> +                buyerAccessToken = await createNewAccessToken({ orderID, facilitatorAccessToken, buyerAccessToken });
Lets use upgradeFacilitatorAccessTokenWithIgnoreCache(...) directly 

Also mutation returns the new `facilitatorAccessToken` which should be passed when calling `captureOrder` on line 186.

2023-09-25 19:56 UTC, ravishekhar commented on src/props/onApprove.js
> +                buyerAccessToken = await createNewAccessToken({ orderID, facilitatorAccessToken, buyerAccessToken });
Same comment as above. Lets use upgradeFacilitatorAccessTokenWithIgnoreCache(...) directly 

Also mutation returns the new `facilitatorAccessToken` which should be passed when calling `authorizeOrder` on line 207.

2023-09-25 19:56 UTC, ravishekhar commented on src/props/onApprove.js
> +                buyerAccessToken = await createNewAccessToken({ orderID, facilitatorAccessToken, buyerAccessToken });
Same comment as above. Lets use upgradeFacilitatorAccessTokenWithIgnoreCache(...) directly 

Also mutation returns the new `facilitatorAccessToken` which should be passed when calling `patchOrder` on line 221.

2023-09-25 19:56 UTC, ravishekhar commented on src/api/auth.js
> +            throw err;
Lets not throw error as the clients can use it in path of capturing or getting order details, lets just log it using beaver logger. 

Also pls follow the above sample to set the lsat upgrade error flag `onLsatUpgradeError(err);`

2023-09-25 19:56 UTC, ravishekhar commented on src/api/auth.js
> +    return inlineMemoize(upgradeFacilitatorAccessTokenWithIgnoreCache, () => {
Can you pls test and ensure the `inlineMemoize` will not return the memoized value of any of params like `facilitatorAccessToken`, `buyerAccessToken` or `orderID` changes.

2023-09-25 19:56 UTC, ravishekhar commented on src/api/auth.js
> +        return callGraphQL({
Before calling graphql, set the appropriate flags.
```
clearLsatState();
onLsatUpgradeCalled();
```

2023-09-25 19:56 UTC, ravishekhar commented on src/props/onApprove.js
> +                buyerAccessToken = await createNewAccessToken({ orderID, facilitatorAccessToken, buyerAccessToken });
Lets use upgradeFacilitatorAccessTokenWithIgnoreCache(...) directly 

Also mutation returns the new `facilitatorAccessToken` which should be passed when calling `getOrder` on line 170

2023-09-25 19:56 UTC, ravishekhar commented on src/props/onApprove.js
> +                throw new Error("Cannot create new buyer access token");
Since we would update upgradeFacilitatorAccessTokenWithIgnoreCache(...) to not throw any errors. We can avoid this try catch block.

2023-09-25 19:56 UTC, ravishekhar commented on src/props/onApprove.js
> +    const get = memoize(async() => {
is `async` supported with `memoize` ? can we use the Promise, then/catch syntax if async is not supported?

2023-09-25 19:56 UTC, ravishekhar commented on src/props/onShippingChange.js
> +import {createNewAccessToken} from './onApprove';
Pls use the `upgradeFacilitatorAccessTokenWithIgnoreCache(...) ` from `api/auth` instead of createNewAccessToken.

2023-09-25 19:56 UTC, ravishekhar commented on src/props/onShippingChange.js
> +                buyerAccessToken = await createNewAccessToken({ orderID, facilitatorAccessToken, buyerAccessToken });
Same comment as above. Lets use upgradeFacilitatorAccessTokenWithIgnoreCache(...) directly

Also mutation returns the new facilitatorAccessToken which should be passed when calling patchOrder on line 182.

2023-09-25 19:56 UTC, ravishekhar commented on src/props/onShippingChange.js
> +                throw new Error("Cannot create new buyer access token");
Since we would update upgradeFacilitatorAccessTokenWithIgnoreCache(...) to not throw any errors. We can avoid this try catch block.

2023-09-26 19:07 UTC, wsbrunson commented on src/props/onApprove.js
> +            facilitatorAccessToken = upgradeFacilitatorAccessTokenWithIgnoreCache(facilitatorAccessToken,buyerAccessToken,orderID);
I think we need to `await` any call to `upgradeFacilitatorAccessTokenWithIgnoreCache`

2023-09-26 19:28 UTC, wsbrunson commented on src/props/onApprove.js
> +                    return getOrder(orderID, { facilitatorAccessToken, buyerAccessToken, partnerAttributionID, forceRestAPI, experiments });
I'd suggest the following to make it a little clearer what is happening:
```suggestion
                .then((upgradedFacilitatorAccessToken) => {
                    return getOrder(orderID, { facilitatorAccessToken: upgradedFacilitatorAccessToken, buyerAccessToken, partnerAttributionID, forceRestAPI, experiments });
```

2023-09-27 17:39 UTC, ravishekhar commented on src/api/auth.js
> +          }
At this point the buyer access will be available. We can remove this if condition. 
```suggestion
          headers[HEADERS.ACCESS_TOKEN] = buyerAccessToken;
```

2023-09-27 18:08 UTC, xuanwan05 commented on src/api/auth.js
> +          }
type OrderActionOptions = {|
    orderID : string,
    paymentID : ?string,
    payerID : ?string,
    restart : () => ZalgoPromise<void>,
    intent : $Values<typeof INTENT>,
    facilitatorAccessToken : string,
    buyerAccessToken : ?string,
    partnerAttributionID : ?string,
    forceRestAPI : boolean,
    onError : OnError,
    experiments: Experiments
|};

function buildOrderActions({ intent, orderID, restart, facilitatorAccessToken, buyerAccessToken, partnerAttributionID, forceRestAPI, onError, experiments } : OrderActionOptions) : OrderActions {
    const get = memoize(() => {
        if (experiments?.upgradeLSATWithIgnoreCache) {
            return upgradeFacilitatorAccessTokenWithIgnoreCache(facilitatorAccessToken, buyerAccessToken, orderID)
   

buyerAccessToken is optional, so when we pass it to upgradeFacilitatorAccessTokenWithIgnoreCache, the value could be undefined or null.

2023-09-27 18:38 UTC, ravishekhar commented on src/api/auth.js
> +          }
We should make it mandatory. Without this data the mutation will fail.

2023-10-02 18:44 UTC, ravishekhar requested changes

2023-10-02 18:44 UTC, ravishekhar commented on src/props/onApprovePatchAction.test.js
> +    expect(callGraphQL).toHaveBeenCalled();
can you pls add validation to check if right graphql mutation was called.

2023-10-02 18:44 UTC, ravishekhar commented on src/props/onApprovePatchAction.test.js
> +    await order.patch();
Pls assert if v2 orders api was called when calling patch

2023-10-02 19:52 UTC, elizabethmv reviewed
Mostly clean up comments, looking good so far!

2023-10-02 19:52 UTC, elizabethmv commented on src/api/auth.js
> +            getLogger().info('upgradeFacilitatorAccessTokenWithIgnoreCache returns successfully');
```suggestion
```
This log looks off, but also I don't think we need to add any success logs here. I would recommend removing it.

2023-10-02 19:52 UTC, elizabethmv commented on src/props/onApprove.test.js
> +          btSdkOrdersV2Migration: true,
```suggestion
```
Is this needed? It looks more like carry over.

2023-10-02 19:52 UTC, elizabethmv commented on src/props/onApprove.test.js
> +          btSdkOrdersV2Migration: true,
```suggestion
```
Same comment about needing this here.

2023-10-02 19:52 UTC, elizabethmv commented on src/props/onApproveGetAction.test.js
> +    // Expect the mock to have been called
I would recommend removing all of the "Expect the mock to have been called" comments, the assertion reads the same.
```suggestion
```

2023-10-02 22:54 UTC, xuanwan05 commented on src/props/onApprove.test.js
> +          btSdkOrdersV2Migration: true,
it's needed, otherwise it fails at `merchantOnApprove` check

2023-10-03 14:28 UTC, jshawl commented on src/props/onApprove.test.js
> +          btSdkOrdersV2Migration: true,
I think you can remove `btSdkOrdersV2Migration` here but then in the `expect` down below, remove `paymentID: "abc123"` - fwiw I am hoping to remove this experiment altogether in this sprint so I imagine this test will be updated to account for that (`paymentID` will always be the `orderID` but without the `EC-` prefix)

2023-10-04 22:15 UTC, ravishekhar approved these changes
Looks good 👍 . Lets create a followup PR to address the gaps in unit tests.

2023-10-04 22:15 UTC, ravishekhar commented on src/props/onApprove.js
> +export function buildXApproveOrderActions({ intent, orderID, paymentID, payerID, restart, facilitatorAccessToken, buyerAccessToken, partnerAttributionID, forceRestAPI, onError, experiments } : Approv
Lets create a followup PR to add test cases for public method getOnApproveOrder and remove this private method from being exported.

2023-10-05 18:16 UTC, elizabethmv approved these changes

2023-10-05 18:21 UTC, merged