[DTPPCPSDK-1328] Remove old LSAT code
paypal/paypal-smart-payment-buttons pull request #706
Opened 2023-10-27 21:42 UTC by xuanwan05

### Description
With the introduction and 100% ramp of using CreateUpgradedLowScopeAccessToken mutation, usage of UpgradeFacilitatorAccessToken mutation is no longer needed.

Clean up 

Any method using that mutation e.g. upgradeFacilitatorAccessToken

The logic insidegetOnAuth from props/onAuth.js module can be removed, ensure that this module continues to return a resolved promise with accessToken and the logs spb_onauth_access_token_present/not_present are emitted. Also the method must set the access to cache using setBuyerAccessToken

### Why are we making these changes? Include references to any related Jira tasks or GitHub Issues

### Reproduction Steps (if applicable)

### Screenshots (if applicable)

### Dependent Changes (if applicable)

### Groups who should review (if applicable)

❤️  Thank you!

2023-10-30 22:41 UTC, ravishekhar requested changes

2023-10-30 22:41 UTC, ravishekhar commented on src/props/onApprove.test.js
> -    test("invoke upgradeFacilitatorAccessTokenWithIgnoreCache call if treatment is present", async () => {
Since the default use case now is always upgradeFacilitatorAccessTokenWithIgnoreCache() to be called, so I assume we need a test validating the code path.

2023-10-30 22:41 UTC, ravishekhar commented on src/props/onAuth.js
> +                if (createSubscription ) {
I think we can even remove this `if (createSubscription )` condition right ? 
We need to ensure we are caching 
`setBuyerAccessToken(accessToken);` for all cases now, as `isInIgnoreCacheExperiment` is always `true` after experiment is ramped to 100%.

2023-10-30 22:41 UTC, ravishekhar commented on src/props/onAuth.js
>                      getLogger().info("ignore_lsat_upgrade", {
we can remove this log, as we always ignore lsat upgrade at this point

2023-11-07 21:10 UTC, mnicpt commented
@xuanwan05 There is a ton of changes outside of removing old LSAT code. Are we applying a different lint? I almost feel like the cleanup should happen in another PR and describing what is being cleaned up.

2023-11-07 21:44 UTC, ravishekhar commented
> @xuanwan05 There is a ton of changes outside of removing old LSAT code. Are we applying a different lint? I almost feel like the cleanup should happen in another PR and describing what is being cleaned up.

@mnicpt We are in mid of reformatting this PR as per newly formatted  files in main branch after prettier run.

2023-11-08 15:17 UTC, closed without merging